apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pelago
  name: registry-deployment
  labels:
    app: registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2.7.0
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: registry-auth
              key: HTTP_SECRET
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
        - name: REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR
          value: "redis"
        - name: REGISTRY_REDIS_ADDR
          value: "redis-service.pelago.svc.cluster.local:6379"
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        volumeMounts:
        - name: tls
          mountPath: "/certs"
          readOnly: true
        - name: htpasswd
          mountPath: /auth
          readOnly: true
        - name: storage
          mountPath: /var/lib/registry
      volumes:
      - name: tls
        secret:
          secretName: registry-tls
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
      - name: htpasswd
        secret:
          secretName: registry-auth
          items:
          - key: HTPASSWD
            path: htpasswd
      - name: storage
        hostPath: 
          path: /run/desktop/mnt/host/c/Users/Mark/Documents/Interview/Pelago/registry/storage
          type: DirectoryOrCreate
