apiVersion: v1
kind: Secret
metadata:
  name: registry-creds
  namespace: pelago
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJsb2NhbGhvc3Q6MzAwMDciOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiYWRtaW5wYXNzd29yZCIsImVtYWlsIjoiYWRtaW5AcGVsYWdvLmNvIiwiYXV0aCI6IllXUnRhVzQ2WVdSdGFXNXdZWE56ZDI5eVpBPT0ifX19
