apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pelago
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine3.13
        command: ["redis-server", "--appendonly", "yes"]
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        hostPath: 
          path: /run/desktop/mnt/host/c/Users/Mark/Documents/Interview/Pelago/registry/redis-storage
          type: DirectoryOrCreate
